# Generated by Django 3.2.8 on 2021-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
