# Generated by Django 3.2.8 on 2021-10-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_artist',
            new_name='artist',
        ),
    ]
